name: coverage

on:
  push:
    branches: [ master ]

jobs:
  coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn coverage
